<?php

namespace MaitreOeuvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChantierRepository extends EntityRepository
{
}
