<?php

namespace MaitreOeuvreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeChantierRepository extends EntityRepository
{
}
