<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function listeMembres($role)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.roles LIKE :ROLE');
//        $qb->orderBy('p.prenom','DESC');
        $qb->setParameter('ROLE', '%'.$role.'%');

        return $qb->getQuery()->getResult();
    }
}
